spring:
  datasource:
    # jdbc:mysql://teamwork:3306/charityquest?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    url: ENC(YERBAnLL11Ndw9b1MUpn490fKSpdtxmz84clnVEgjh+i2QK6x8v7U5KX8vbZaJONsf0jTradg5NR94jcVxFQCdDyK/jfEY5FWR4Q5/mh/f+cdcGju1gqaoNuaDXibcDwaHhGfwqi7Pe+sU6ZFbos0/5LspZVSTHp)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(qZLZHAuivt5WKkSIBt13Xw==)
    password: ENC(tl4hpYD1qLYh9pV2VpJbVg37uXb9/+dHYW0x+3AVLvc=)
    hikari:
      connection-test-query: SELECT 1
      validation-timeout: 5000
      idle-timeout: 0
      maximum-pool-size: 10
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            instanceName: CharityQuestScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: false
            clusterCheckinInterval: 10000
            useProperties: true
          #          dataSource:
          #            default:
          #              provider: hikaricp
          #              #URL: jdbc:mysql://teamwork:3306/charityquartz?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
          #              #ENC(zmREIHPLd8oKNflOyYx/6pPYzWPgXh1gaHVKFGhu9WGoZYtrolew9znBOt6wX1Xbdil5J8veLXkryYL/UVRK0eKTYlnJCiiC9OdUGdWAApvRZZxGe7OSn32gfPjR56FIalKPbEOOzeM4P6JqGWI+H5lTibpo/inH)
          #              URL: ENC(YERBAnLL11Ndw9b1MUpn490fKSpdtxmz84clnVEgjh+i2QK6x8v7U5KX8vbZaJONsf0jTradg5NR94jcVxFQCdDyK/jfEY5FWR4Q5/mh/f+cdcGju1gqaoNuaDXibcDwaHhGfwqi7Pe+sU6ZFbos0/5LspZVSTHp)
          #              driver: com.mysql.cj.jdbc.Driver
          #              user: ENC(qZLZHAuivt5WKkSIBt13Xw==)
          #              password: ENC(tl4hpYD1qLYh9pV2VpJbVg37uXb9/+dHYW0x+3AVLvc=)
          #              maximumPoolSize: 10
          #              connectionTestQuery: SELECT 1
          #              validationTimeout: 5000
          #              idleTimeout: 0
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
server:
  port: 7777
  servlet:
    context-path: /CharityQuest

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

jasypt:
  encryptor:
    password: Sheffiled@Team17

mybatis:
  mapper-locations: classpath:mapper/*.xml