spring:
  datasource:
    url: ENC(YERBAnLL11Ndw9b1MUpn490fKSpdtxmz84clnVEgjh+i2QK6x8v7U5KX8vbZaJONsf0jTradg5NR94jcVxFQCdDyK/jfEY5FWR4Q5/mh/f+cdcGju1gqaoNuaDXibcDwaHhGfwqi7Pe+sU6ZFbos0/5LspZVSTHp)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(qZLZHAuivt5WKkSIBt13Xw==)
    password: ENC(tl4hpYD1qLYh9pV2VpJbVg37uXb9/+dHYW0x+3AVLvc=)
    hikari:
      connection-test-query: SELECT 1
      validation-timeout: 5000
      idle-timeout: 0
      maximum-pool-size: 10
  jackson:
    visibility.field: any
    visibility.getter: none
    visibility.setter: none

server:
  port: 7777
  servlet:
    context-path: /CharityQuest
    session:
      timeout: 60m

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

jasypt:
  encryptor:
    password: Sheffiled@Team17

mybatis:
  mapper-locations: classpath:mapper/*.xml

code:
  expire: 1440 # minutes
  base-url: http://localhost:8080/
