spring:
  datasource:
    url: ENC(YERBAnLL11Ndw9b1MUpn490fKSpdtxmz84clnVEgjh+i2QK6x8v7U5KX8vbZaJONsf0jTradg5NR94jcVxFQCdDyK/jfEY5FWR4Q5/mh/f+cdcGju1gqaoNuaDXibcDwaHhGfwqi7Pe+sU6ZFbos0/5LspZVSTHp)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(qZLZHAuivt5WKkSIBt13Xw==)
    password: ENC(tl4hpYD1qLYh9pV2VpJbVg37uXb9/+dHYW0x+3AVLvc=)
    hikari:
      connection-test-query: SELECT 1
      validation-timeout: 5000
      idle-timeout: 0
      maximum-pool-size: 10
  jackson:
    visibility.field: any
    visibility.getter: none
    visibility.setter: none
  mail:
    host: smtp.gmail.com
    port: 465
    username: ENC(3aOVMaCdyNVk/NCm7DQky+wYQA3qdiipjpGs8Kg4Hxc=)
    # ohfmwxisvspzgwxq
    password: ENC(z7jkGBL3g8IyHyj1X/49FqnxF4Z33wn/aRTI4q5X5aU=)
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  port: 7777
  servlet:
    context-path: /CharityQuest
    session:
      timeout: 60m

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

jasypt:
  encryptor:
    password: Sheffiled@Team17

mybatis:
  mapper-locations: classpath:mapper/*.xml

code:
  expire: 1440 # minutes
  base-url: http://localhost:8080/
